# Generated by Django 4.0.5 on 2022-07-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='following',
            name='user',
        ),
        migrations.AddField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
